INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_MODULATION Modulation)

FIND_PATH(
    MODULATION_INCLUDE_DIRS
    NAMES Modulation/api.h
    HINTS $ENV{MODULATION_DIR}/include
        ${PC_MODULATION_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    MODULATION_LIBRARIES
    NAMES gnuradio-Modulation
    HINTS $ENV{MODULATION_DIR}/lib
        ${PC_MODULATION_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MODULATION DEFAULT_MSG MODULATION_LIBRARIES MODULATION_INCLUDE_DIRS)
MARK_AS_ADVANCED(MODULATION_LIBRARIES MODULATION_INCLUDE_DIRS)

